### ISSUE TITLE
merging with compiler

### ISSUE THREAD

**Issue by wontruefree** [636f7374/stdlib.cr#1]
I am curious have you opened some of these patches back to the crystal core repo?

**Comment by 636f7374** [comment]
@wontruefree 

No, these have only been tested by me and have some features that Crystal does not have. 

* OpenSSL Features
  * SSL ((Socket, Context) Without finalizer, free up memory manually).
  * Other (X.509 Generate Certificate, MITM, MemBIO).
* DNS
  * DNS resolver with cache, Used to solve C.getaddrinfo stuck problem.
  * References: [#8376](https://github.com/crystal-lang/crystal/issues/8376).
* WebSocket
  * Can control whether to send (ping, close) packets automatically.
* HTTP
  * HTTP::Client ((Socket, Context) Without finalizer, free up memory manually).
  * HTTP::Request (Supports HTTP 100 Continue (automatically)).
  * HTTP::Server (Can set client read / write timeout) (Preventing slow reading attacks).
* Gzip
  * Gzip damage repair.
* Too many, I won't list them one by one.

All of these `issues` have been raised, and you may need to wait two years to fix some of them?

I created a tool similar to MITMProxy, but I did n’t expect to encounter so many problems (in Crystal-language).

If you encounter the above problem, you can try using `stdlib.cr`, Currently this repository is only for me.

Once my tool is complete, I may split this repository (E.g. OpenSSL, DNS :: Resolver).

So good luck, if give me another chance, I will choose rust-language.

All this issue you can find in Crystal-lang issues.


I need these features, but crystal won't be added, maybe after 1 - 2 years?

If there are other issues, please open this issue again. 🙂

**Comment by 636f7374** [comment]
@wontruefree 

I ’m sorry for my slow reply during this period, I was too busy creating DNS::Resolver, so I could n’t reply to you immediately. :)
